# Lec110 : Link Analysis (Continued) - Convergence in Repeated Matrix Multiplication (Pre-Requisite 1 )


In [4]:
import numpy as np

A = np.mat('1 2; 3 4')
v = np.mat('1; 1')

print A*v

[[3]
 [7]]


In [5]:
import numpy as np

A = np.mat('1 2; 3 4')
v = np.mat('1; 1')
print v
print "#"*20
for i in range(10):
    z = A*v
    z = z/np.linalg.norm(z)#denominator sqrt(a^2+ b^2)
    v = z
    print z
    print "*"*20


[[1]
 [1]]
####################
[[ 0.3939193 ]
 [ 0.91914503]]
********************
[[ 0.41750017]
 [ 0.90867684]]
********************
[[ 0.41586776]
 [ 0.9094251 ]]
********************
[[ 0.41598089]
 [ 0.90937336]]
********************
[[ 0.41597305]
 [ 0.90937694]]
********************
[[ 0.41597359]
 [ 0.90937669]]
********************
[[ 0.41597356]
 [ 0.90937671]]
********************
[[ 0.41597356]
 [ 0.90937671]]
********************
[[ 0.41597356]
 [ 0.90937671]]
********************
[[ 0.41597356]
 [ 0.90937671]]
********************


In [6]:
import numpy as np

A = np.mat('1 2; 3 4')
v = np.mat('4; 11')
print v
print "#"*20
for i in range(10):
    z = A*v
    z = z/np.linalg.norm(z)#denominator sqrt(a^2+ b^2)
    v = z
    print z
    print "*"*20

[[ 4]
 [11]]
####################
[[ 0.42111131]
 [ 0.90700897]]
********************
[[ 0.41561741]
 [ 0.90953954]]
********************
[[ 0.41599824]
 [ 0.90936542]]
********************
[[ 0.41597185]
 [ 0.90937749]]
********************
[[ 0.41597368]
 [ 0.90937665]]
********************
[[ 0.41597355]
 [ 0.90937671]]
********************
[[ 0.41597356]
 [ 0.90937671]]
********************
[[ 0.41597356]
 [ 0.90937671]]
********************
[[ 0.41597356]
 [ 0.90937671]]
********************
[[ 0.41597356]
 [ 0.90937671]]
********************


* Inference : No matter where we start from(v), A converges to a constant vector